### ISSUE TITLE
Unable to add internal user to a project

### ISSUE THREAD

**Issue by pcheliniy** [BESTSELLER/terraform-provider-harbor#12]
Hi.
We have some problems with internal users, provider crashes when we try to add a new user to a project.
tf code which provide error
```
resource "harbor_project_member" "project_member" {
  project_id    = harbor_project.project["core"].id
  name          = "core"
  role          = "developer"
  type          = "internal"
}
```
Plan is generated without any problem but when we try to apply it we got crash and following error https://gist.github.com/pcheliniy/b68acdecc697cfc88e40dd06a6ca2818
provider version: 0.1.1
api_version: 2
harbor doesn't have clair and trivy components (I'm not sure but I guess it can be connected to the problem)
vulnerability scanning for project also disabled (we tried to enable it but it didn't help)

**Comment by brett-wright** [comment]
Hi @pcheliniy 

This resource wasn't design to be used with users so I've created 2 more resources harbor_project_member_group and harbor_project_member_user.

I will be deprecating harbor_project_member in later version of this provider.

Cheers,

Brett Wright
