### ISSUE TITLE
Unclear description for email_insecure

### ISSUE THREAD

**Issue by lindhe** [BESTSELLER/terraform-provider-harbor#132]
The description for the `email_insecure` argument in [the `harbor_config_email` resource](https://github.com/BESTSELLER/terraform-provider-harbor/blob/469bd6c2f4e0586017d1d1522f121a4a961916f5/docs/resources/config_email.md) is very confusing to me:
> **email_insecure** - (Optional) Verify Certificate for email server connection

I assume this is a boolean flag that allows for bad certificate if set to `true`. But the description indicates that setting the argument (to something?) enables verification of certificates.

**Comment by wrighbr** [comment]
@lindhe Its a bool value. by default it set to false

**Comment by lindhe** [comment]
Would you be open for a PR that tries to clarify this? :)

**Comment by wrighbr** [comment]
@lindhe feel free to open PR
