### ISSUE TITLE
Allow setting up "prevent vulnerable images from running"

### ISSUE THREAD

**Issue by michalformanek** [BESTSELLER/terraform-provider-harbor#141]
harbor_project resource allows enabling content trust (enable_content_trust  = "true" or "false") or triggering vulnerability scanning on push (vulnerability_scanning = "true" or "false"). Under harbor project configuration, there is also "Deployment security" - "Prevent vulnerable images from running." Would it be possible to extend harbor_project and add this option?

**Comment by dweebo** [comment]
You can configure that with the `deployment_security` field

```hcl
resource "harbor_project" "test" {
  name                    = "test"
  public                  = true
  storage_quota           =-1
  vulnerability_scanning  = true
  deployment_security     = "Medium"
}
```

**Comment by wrighbr** [comment]
feature allready done
