### ISSUE TITLE
Allow multiple actions for robot user

### ISSUE THREAD

**Issue by tomfankhaenel** [BESTSELLER/terraform-provider-harbor#16]
**Current situation**
A robot user can be created but only with a single action
```
resource "haror_project" "main" {
    name = "main"
}

resource "harbor_robot_account" "account" {
  name        = "${harbor_project.main.name}"
  description = "Robot account used to push images to harbor"
  project_id  = harbor_project.main.id
  action      = "push"
}
```
In harbor a robot account can be created with more than one action. 
* push (docker)
* read (helm)
* create (helm)

**Desired situation**
Please enable creation of a robot account allowing multiple acctions. For example like this.
```
resource "haror_project" "main" {
    name = "main"
}

resource "harbor_robot_account" "account" {
  name        = "${harbor_project.main.name}"
  description = "Robot account used to push images to harbor"
  project_id  = harbor_project.main.id
  action      = ["push","create","read"]
}
```
**To be changed**
As far as i understood the RobotBodyAccess in RobotBody must be adjusted to send a json with multiple actions instead of a single action like this.

```
{
  "name": "testrobot",
  "expires_at": -1,
  "description": "t",
  "access": [
    {
      "resource": "/project/3/repository",
      "action": "push"
    },
    {
      "resource": "/project/3/helm-chart",
      "action": "read"
    },
    {
      "resource": "/project/3/helm-chart-version",
      "action": "create"
    }
  ]
}
```

**Comment by wrighbr** [comment]
Have created a attribute called actions where you can define a list actions for the robbot account

**Comment by tomfankhaenel** [comment]
Perfect, works as expected :) Thank you for the fast reaction.
