### ISSUE TITLE
harbor_project_member_user doesn't work with api v2

### ISSUE THREAD

**Issue by sshota0809** [BESTSELLER/terraform-provider-harbor#168]
**Describe the bug**
With api v2, `harbor_project_member_user` module doesn't work because of 404 not found error.

**To Reproduce**
1. Set api version as v2
2. Configure `.tf` file using `harbor_project_member_user` module
3. Plan & Apply

**Expected behavior**
Apply would work

**Desktop (please complete the following information):**
 - OS: mac 10.15.2
 - Terraform: v0.15.5

**Harbor Version:**
 - Core: v2.3.0

**My Research**
As following code, tarraform provider will try to access harbor api with path `/api/v2.0/<project id>/members`.

https://github.com/BESTSELLER/terraform-provider-harbor/blob/5b144f24c4b2df0ba389daf2c52b85f2b18748fe/provider/resource_project_member_user.go#L50

But according to harbor api document, provider should access api with path `/api/v2.0/projects/<project id>/members`.

![horbor api document v2](https://user-images.githubusercontent.com/8736380/145737937-ba61eca5-0650-466d-b62d-75bc6d88829c.png)

After I modified source code and rebuild in my local laptop so that provider access above path, I have confirmed it worked!

But, I'm not sure that `/api/<project id>/members` is correct on harbor v1 api. If so I have to use conditional branch by api version. I am not using harbor v1, so I cannot check v1 api document, but if I get it I would create PR.

I want someone to let me know about v1 api!

**Comment by wrighbr** [comment]
@sshota0809  Please feel free to create a PR.
I think most people aren't using the v1 api as it quite old.

**Comment by sshota0809** [comment]
@wrighbr 
Thank you for your reply.
OK, I will create PR that match v2 api. Please wait a while.

**Comment by sshota0809** [comment]
Thanks a lot for merging, I'll close this issue.
