### ISSUE TITLE
Event Based type of replication

### ISSUE THREAD

**Issue by aldiserg** [BESTSELLER/terraform-provider-harbor#171]
Event Based type of replication needed for replicating changed images (artifacts) to the remote registry immediately

Official docs like https://goharbor.io/docs/2.4.0/administration/configuring-replication/create-replication-rules/

**Comment by wrighbr** [comment]
@aldiserg I'm pretty sure you can already event_based replication in the harbor_replication resource in the schedule argument you can put event_based its just not documented

**Comment by aldiserg** [comment]
yeap, it's work, thank you a lot =)
