### ISSUE TITLE
When server returns a 500 error resource is removed from state but cannot be recreated when server is back up

### ISSUE THREAD

**Issue by gmintoco** [BESTSELLER/terraform-provider-harbor#192]
**Describe the bug**
If the harbor server goes down when terraform is applying and returns a 500 error (in particular 502 and 504) those resources are removed from the statefile and the provider attempts to recreate them on the next apply. This causes issues as those resources still exist in harbor they just weren't accessible before due to networking or load balancer issues.

If the server returns anything but a 404 error for a particular ID then IMO the provider should just return an error instead of trying to recreate the resource.

**To Reproduce**
1. Create a project using a project resource. Run apply
2. Get the service to return a 504 (easy way is to remove the service resource in K8s)
3. Reapply and notice how it identifies those resources are "gone" and it removes them from the statefile, and then attempts to recreate them.
4. Recreate the service so harbor is up again and rerun the apply job and notice how the creation of the resources fail because they already exist.

**Expected behavior**
The provider should fail if anything but a 404 or 200 is returned from the API. As anything other than these indicate that the request wasn't processed properly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by defreng** [comment]
we're also running into these issues when using the provider - especially when connecting to Harbor instances that are geographically "far away" (on the other side of the world)...

Since the issues are appearing so sporadically, we weren't yet able to figure out the exact nature of the problem, but I highly suspect some non-standard HTTP return codes or some connection timeouts/aborts.

Here's an excerpt from such a failing `terraform apply` run:

```
[...]
- Using bestseller/harbor v3.5.0 from the shared cache directory
[...]
module.abc.harbor_robot_account.docker_pull: Refreshing state... [id=/robots/154]
[...]
# module.abc.harbor_robot_account.docker_pull has been deleted
  - resource "harbor_robot_account" "docker_pull" {
      - disable     = false -> null
      - duration    = -1 -> null
      - robot_id    = "154" -> null
      - secret      = (sensitive value)
      - permissions {
[...]
# module.abc.harbor_robot_account.docker_pull will be created
  + resource "harbor_robot_account" "docker_pull" {
      + disable     = false
      + duration    = -1
      + full_name   = (known after apply)
      + id          = (known after apply)
      + level       = "system"
[...]
│ Error: [ERROR] unexpected status code got: 409 expected: 201 
│  {"errors":[{"code":"CONFLICT","message":"robot account 0:docker-pull already exists"}]}
│ 
│ 
│   with module.abc.harbor_robot_account.docker_pull,
```
