### ISSUE TITLE
Support Limited Guest Role

### ISSUE THREAD

**Issue by overmike** [BESTSELLER/terraform-provider-harbor#20]
**Is your feature request related to a problem? Please describe.**
Currently, I can't specify Limited guest in the string type role of project_member_group and project_member_user

`Error: "role" must be either projectadmin, developer, guest or master, got: limitedguest`

**Describe the solution you'd like**
Support limited guest on role

**Describe alternatives you've considered**
There is no terraform alternative, but manually set this up on portal

**Additional context**

**Comment by wrighbr** [comment]
@overmike in release v0.5.1 you can now add  limitedguest to these resources

**Comment by overmike** [comment]
Thanks for the effort 🙏👍
