### ISSUE TITLE
issue while creating email configuration

### ISSUE THREAD

**Issue by flbla** [BESTSELLER/terraform-provider-harbor#22]
Hi,
Thanks for this project!
I had the following issue when trying to configure email.

**Describe the bug**
I tried to use: harbor_config_email, but I got this error and a stacktrace :
`panic: interface conversion: interface {} is string, not int`

**To Reproduce**
1. add a `harbor_config_email `resources with : 
```
email_host
email_port
email_username
email_password
email_from
email_ssl
```
2. `terraform apply`

**Expected behavior**
Email configuration is applied on harbor

**Desktop (please complete the following information):**
 - OS: windows10
 - Terraform v0.13.5
 - provider registry.terraform.io/bestseller/harbor v0.5.1

**Comment by wrighbr** [comment]
@flbla I've fixed this bug in v0.5.2

**Comment by flbla** [comment]
thanks! :)

this is not good too : https://github.com/BESTSELLER/terraform-provider-harbor/blob/master/provider/resource_config_email.go#L35
should be TypeBool, I got a panic error because of this too

furthermore it seems all boolean parameters are not working (like email_ssl and oidc_verify_cert)
do you have any idea why?

**Comment by flbla** [comment]
seems to be because of this `omitempty`
https://github.com/BESTSELLER/terraform-provider-harbor/blob/master/models/config.go#L44
