### ISSUE TITLE
Harbor Garbage Collection configuration

### ISSUE THREAD

**Issue by flbla** [BESTSELLER/terraform-provider-harbor#26]
**Is your feature request related to a problem? Please describe.**
It's not possible to configure with this TF provider, garbage collect on Harbor

**Describe the solution you'd like**
Be able to configure this with Terraform :
![image](https://user-images.githubusercontent.com/11298399/98223820-ef72f580-1f52-11eb-8b74-0d01c1e31334.png)

**Comment by wrighbr** [comment]
I have this todo in our backlog for this provider. I can try and prioritise this.
