### ISSUE TITLE
Harbor Project Policy configuration

### ISSUE THREAD

**Issue by flbla** [BESTSELLER/terraform-provider-harbor#27]
Hello,

**Describe the solution you'd like**
I would like to be able to configure project policy (retention and immutability) :
![image](https://user-images.githubusercontent.com/11298399/98224210-8049d100-1f53-11eb-9b5d-fb83ea2ea1f0.png)

**Comment by wrighbr** [comment]
I have this todo in our backlog for this provider. I can try and prioritise this.

**Comment by wrighbr** [comment]
I have this todo in our backlog for this provider. I can try and prioritise this.
