### ISSUE TITLE
Custom cron => Garbage collect changed every time

### ISSUE THREAD

**Issue by flbla** [BESTSELLER/terraform-provider-harbor#31]
Hi,
When I use a custom cron, it is applied at every launch of Terraform
Because of this :
https://github.com/BESTSELLER/terraform-provider-harbor/blob/6973f96dba6f3af50eb4e61bfdacf38490264d77/provider/resource_garbage_collection.go#L66 
which is set to "custom"

**Comment by wrighbr** [comment]
I've merged the pull request.
