### ISSUE TITLE
[update documentation] custom cron expressions for harbor_interrogation_services

### ISSUE THREAD

**Issue by tomfankhaenel** [BESTSELLER/terraform-provider-harbor#47]
**Current state**
The Interrogation Services can be configured to use preconfigured schedules like described [here](https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/interrogation_services)

It can also use custom cron expressions like in the UI and API but it is not mentioned in the documentation.
![image](https://user-images.githubusercontent.com/35062114/102777401-cc7c9380-4390-11eb-9aa1-bd086f4cd2ac.png)

**Request**
It would be very good to know this feature is implemented in case you need a more specific cron expression or at a different time during the day.

**Comment by wrighbr** [comment]
@tomfankhaenel I actually think it accepts a cron string for argument vulnerability_scan_policy. But it's just not documented.

**Comment by tomfankhaenel** [comment]
> @tomfankhaenel I actually think it accepts a cron string for argument vulnerability_scan_policy. But it's just not documented.

I should have tested this first :D Thanks, it worked as described.
In that case the request would be to add this feature to the description ;)
