### ISSUE TITLE
Resource harbor_group unsupported

### ISSUE THREAD

**Issue by jakuboskera** [BESTSELLER/terraform-provider-harbor#54]
It would be good if we can create resource `harbor_group`. We are managing Harbor users via LDAP groups, so we cannot use this provider for this purposes.

**Comment by wrighbr** [comment]
@jakuboskera you can use harbor_project_member_group to add an ldap group to a project

**Comment by jakuboskera** [comment]
@wrighbr so even if I don't manually add AD group into Groups "registry" via WEB UI, I will be able to assign AD group to project? And then the AD group will be automatically created in Groups "registry"?

**Comment by wrighbr** [comment]
In the linked pull request I've added the the argument ldap_group_dn for the resource harbor_project_member_group

**Comment by jakuboskera** [comment]
Thanks

**Comment by jakuboskera** [comment]
I just found a bug. When I have no LDAP group in Web UI **Administration -> Groups**, I am able to create project along with LDAP group without problems, this is configuration of resources
 
```terraform
resource "harbor_project" "developers" {
  name = "developers"
  public = true
  vulnerability_scanning = true
}

resource "harbor_project_member_group" "developers" {
  project_id    = harbor_project.developers.id
  group_name    = "App_Harbor_developers"
  role          = "developer"
  type          = "ldap"
  ldap_group_dn = "CN=App_Harbor_developers,OU=Apps,DC=contoso,DC=com"
}
```

I perform this command to apply two resources above
```bash
$ terraform apply -auto-approve
harbor_project.developers: Creating...
harbor_project.developers: Creation complete after 1s [id=/projects/2]
harbor_project_member_group.developers: Creating...
harbor_project_member_group.developers: Creation complete after 1s [id=/projects/2/members/2]
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Project and group have been successfully created. Then I comment that two resources (I want delete them from Harbor), I perform again
```bash
$ terraform apply -auto-approve
harbor_project_member_group.developers: Destroying... [id=/projects/2/members/2]
harbor_project_member_group.developers: Destruction complete after 0s
harbor_project.devops: Destroying... [id=/projects/2]
harbor_project.devops: Destruction complete after 1s
Apply complete! Resources: 0 added, 0 changed, 2 destroyed.
```
Now the project has been deleted in Web UI but the LDAP group still persists in Web UI **Administration -> Groups**, it is ok, the group can be there. But when I uncomment the resources above (I want create them again) and perform again the changes, this is output
```bash
$ terraform apply -auto-approve
harbor_project.developers: Creating...
harbor_project.developers: Creation complete after 1s [id=/projects/3]
harbor_project_member_group.developers: Creating...

Error: [ERROR] unexpected status code got: 409 expected: 201 
 {"errors":[{"code":"CONFLICT","message":"Failed to add project member, already exist group or project member, groupDN:CN=App_Harbor_developers,OU=Apps,DC=contoso,DC=com"}]}
```

After this, the project is created successfully again, but the project has no assigned project member group **App_Harbor_developers**.

**Comment by jakuboskera** [comment]
@wrighbr can you reopen this one please? See bug above. Or should I open new issue? I've test the behaviour on the latest version of provider but the bug persist.
