### ISSUE TITLE
Cannot create robot accounts for private projects

### ISSUE THREAD

**Issue by michalformanek** [BESTSELLER/terraform-provider-harbor#59]
We have existing project that we want to gradually migrate to this provider. For public projects, we can create robot accounts like this

data "harbor_project" "project" {
  name   = var.harbor_project_name
}

resource "harbor_robot_account" "account" {
  name        =  var.harbor_robot_account_name
  description = var.harbor_robot_account_description
  project_id  = data.harbor_project.project.id
  actions     = ["pull","read"]
}

For private projects, I get following error

Error: strconv.ParseBool: parsing "": invalid syntax

Is it my hands (I am terraform noob), or actual bug? I am using harbor admin account

**Comment by wrighbr** [comment]
Hi @michalformanek 

What version of the harbor provider are you using?

I'm unable to reproduce the error message with provider version 1.2.0 and harbor version v2.1.1 

Cheers,

Brett Wright

**Comment by michalformanek** [comment]
Hi, @wrighbr 

I did some more refactoring of our code and the issue disappeared, so it was my fault after all :) I'm sorry for bothering you with this. 

Thanks for your provider and keep up the great work
