### ISSUE TITLE
Error when trying to configure of LDAP via resource harbor_config_auth

### ISSUE THREAD

**Issue by jakuboskera** [BESTSELLER/terraform-provider-harbor#61]
I did fresh installation of Harbor v2.1.3. I have used this provider to configure LDAP with local admin account from Harbor.

My configuration of LDAP is following
```hcl
resource "harbor_config_auth" "ldap" {
  auth_mode             = "ldap_auth"
  ldap_url              = "ldaps://example.local:3269"
  ldap_search_dn        = "CN=service_account,OU=srv,DC=example,DC=local"
  ldap_search_password  = var.ldap_search_password
  ldap_base_dn          = "DC=example,DC=local"
  ldap_uid              = "sAMAccountName"
  ldap_scope            = 2
  ldap_group_base_dn    = "OU=Harbor,OU=Apps,DC=example,DC=local"
  ldap_group_admin_dn   = "CN=App_Harbor_Admins,OU=Harbor,OU=Apps,DC=example,DC=local"
  ldap_group_membership = "memberof"
  ldap_group_gid        = "cn"
  ldap_group_scope      = 2
  ldap_verify_cert      = false
}
```

When I apply the resource, I receive this error message
```bash
Error: [ERROR] unexpected status code got: 400 expected: 200 
 {"errors":[{"code":"BAD_REQUEST","message":"configure item is not defined in metadata, item name: ldap_group_id"}]}
```

I tried to add metadata `ldap_group_id = ""` (empty string because I don't know what are valid values) to resource `harbor_config_auth`, but then I receive this error message
```bash
Error: Unsupported argument

  on administration_configuration.tf line 13, in resource "harbor_config_auth" "ldap":
  13:   ldap_group_id        = ""

An argument named "ldap_group_id" is not expected here. Did you mean
"ldap_group_uid"?
```

Am I doing something wrong? I tried to follow the documentation, but currently I am not possible to configure LDAP via this provider.

**Comment by Stainless888** [comment]
Hi 
I have a feeling there is some typo in code.

use ldap settings without option "ldap_group_gid".  Its mapped to non existing option like you have in your message "configure item is not defined in metadata, item name: ldap_group_id"

Hope will solve your problem.

**Comment by Stainless888** [comment]
pull request
https://github.com/BESTSELLER/terraform-provider-harbor/pulls

**Comment by wrighbr** [comment]
Ok Approved the pull request and created a new release.

**Comment by wrighbr** [comment]
@jakuboskera Does this solve your issue?

**Comment by jakuboskera** [comment]
@wrighbr yes, thanks

**Comment by jakuboskera** [comment]
@wrighbr yes, thanks
