### ISSUE TITLE
Filters in the replication are not populating in harbor UI

### ISSUE THREAD

**Issue by rkp2916** [BESTSELLER/terraform-provider-harbor#63]
**Describe the bug**
I used below code to create  registry and replication according to documentation and the filters are populating during the tfplan step but when I see in the UI for the same replication the filters are not present. 

**To Reproduce**
```
provider "harbor" {
  url      = "xxxxx"
  username = "admin"
  password = "xxxx"
}

# registry configuration pull
resource "harbor_registry" "pull" {
  
  provider_name = "docker-hub"
  name          = "Docker Hub"
  endpoint_url  = "https://hub.docker.com"
}

# replication pull based
resource "harbor_replication" "replication_pull" {
  name     = "Jenkins"
  action   = "pull"
  schedule = "0 0 2 * * *"
  filters {
    name     = "jenkins/jenkins"
    tag      = "2.*.{0,1,2,3,4,5,6,7,8,9}-lts-jdk11"
    resource = "image"
  }
  registry_id = harbor_registry.pull.registry_id
}

```
Use the above configuration with `terraform apply`

**Screenshots**
![Screen Shot 2021-01-29 at 4 04 57 PM](https://user-images.githubusercontent.com/20365052/106327401-053f4080-624c-11eb-9998-7e21a1041b41.png)

**Expected behavior**
Filters should reflect in harbor replication.

**Desktop (please complete the following information):**
 - OS: **Linux**

**Smartphone (please complete the following information):** 
 NA

**Additional context**
NA

**Comment by flbla** [comment]
same as : https://github.com/BESTSELLER/terraform-provider-harbor/issues/70

I don't know if it's a bug, but you need to define a filters block for each element

eg:
```
resource "harbor_replication" "replication_pull" {
  name     = "Jenkins"
  action   = "pull"
  schedule = "0 0 2 * * *"
  filters {
    name     = "jenkins/jenkins"
  }
  filters {
    tag      = "2.*.{0,1,2,3,4,5,6,7,8,9}-lts-jdk11"
  }
  filters {
    resource = "image"
  }
  registry_id = harbor_registry.pull.registry_id
}
```
