### ISSUE TITLE
Resource harbor_replication does not support argument trigger

### ISSUE THREAD

**Issue by jakuboskera** [BESTSELLER/terraform-provider-harbor#69]
It is defined as model https://github.com/BESTSELLER/terraform-provider-harbor/blob/274944faf4073369032bdc1d12979073138f8b75/models/replications.go#L15
but not defined in provider https://github.com/BESTSELLER/terraform-provider-harbor/blob/274944faf4073369032bdc1d12979073138f8b75/provider/resource_replication.go#L12

**Comment by flbla** [comment]
I think, what your are looking for is `schedule`
https://github.com/BESTSELLER/terraform-provider-harbor/blob/master/docs/resources/replication.md
for now, you can only set manual or a cron

but with this PR (https://github.com/BESTSELLER/terraform-provider-harbor/pull/76), we should be able to also set event_based for replication

**Comment by jakuboskera** [comment]
Yes that's what I was looking for. Thanks
