### ISSUE TITLE
Resource harbor_replication don't fill name in Source resource filter

### ISSUE THREAD

**Issue by jakuboskera** [BESTSELLER/terraform-provider-harbor#70]
I have specified resource for replication policy below, when I apply it, the replication policy is created in web UI, but the `name` in section `Source resource filter` is empty even it is specified in resource. It should be `test/**`.

```hcl
resource "harbor_replication" "test" {
  name        = "test"
  action      = "push"
  registry_id = harbor_registry.test-harbor.registry_id
  override    = true
  enabled     = true
  filters {
    name      = "test/**"
    resource = "artifact"
  }
}
```

Harbor version: v2.1.1-5f52168e

Terraform version: v0.14.3

**Comment by flbla** [comment]
I don't know if it's a bug, but if you create a filters for each elements, it works

eg:

```
resource "harbor_replication" "test" {
  name        = "test"
  action      = "push"
  registry_id = harbor_registry.test-harbor.registry_id
  override    = true
  enabled     = true
  filters {
    name      = "test/**"
  }
  filters {
    resource = "artifact"
  }
}
```

**Comment by jakuboskera** [comment]
Yes you are right, I had a wrong syntax. It is working perfectly now.
