### ISSUE TITLE
Robot Account Prefix is hardcoded to "robot$"

### ISSUE THREAD

**Issue by sj14** [BESTSELLER/terraform-provider-harbor#84]
**Describe the bug**

The robot prefix is hardcoded to `robot$`.

https://github.com/BESTSELLER/terraform-provider-harbor/blob/54c1a0fe9cb30c554ffcb20dee09a33af67976ee/provider/resource_robot_account.go#L117

Since Harbor 2.2.0 (current only a release candidate), it's possible to adjust this value in the harbor instance configuration. Thus, the hardcoded value in the provider leads to an issue when another prefix is chosen. Syncing the state leads to the recreation of robot accounts each time terraform apply is executed.

**To Reproduce**
1. Go to Habor Web interface as an admin (Harbor version >= 2.2.0)
2. Click on Administration -> Configuration -> System Settings
3. Set "Robot Name Prefix" to something which is not `robot$`
4. Save the changes
5. Apply a terraform configuration with a robot account.

Here, the prefix `robot_` was chosen:

```
  # module.harbor_prod.harbor_robot_account.npp-robot must be replaced
-/+ resource "harbor_robot_account" "npp-robot" {
      ~ id          = "/projects/3/robots/102" -> (known after apply)
      ~ name        = "robot_npp+npp" -> "npp" # forces replacement
      ~ project_id  = "/projects/0" -> "/projects/3" # forces replacement
      ~ robot_id    = "102" -> (known after apply)
      + token       = (sensitive value)
        # (2 unchanged attributes hidden)
    }
```

**Expected behavior**
Any prefix should work and not lead to replacing the robot account in terraform.

Thanks for your work on this project!

**Comment by kschu91** [comment]
I think this one can be closed since https://github.com/BESTSELLER/terraform-provider-harbor/pull/107
