### ISSUE TITLE
Add support for System Level Robot Accounts

### ISSUE THREAD

**Issue by sj14** [BESTSELLER/terraform-provider-harbor#85]
**Is your feature request related to a problem? Please describe.**
Harbor 2.2.0 (current only a release candidate) added the feature of System Level Robot Accounts. It would be beneficial when those accounts could be managed with this provider, too. 

**Describe the solution you'd like**
Adjusting the currently implemented `harbor_robot_account` resource to allow configuring system level robot accounts as well, or adding a new resource type for system level robots. 

**Describe alternatives you've considered**
Managing system level robot accounts manually and outside of terraform.

Thanks for your work on this project!

**Comment by kschu91** [comment]
@sj14 I am currently working on a pull request. Coming soon.

**Comment by kschu91** [comment]
WIP, but already working if someone want to have a look into: https://github.com/kschu91/terraform-provider-harbor/tree/feature/integration-new-robots-api

Documentation: https://github.com/kschu91/terraform-provider-harbor/blob/feature/integration-new-robots-api/docs/resources/robot_account.md
