### ISSUE TITLE
Get Project data object error

### ISSUE THREAD

**Issue by ronny35** [BESTSELLER/terraform-provider-harbor#94]
Hello,

I try to get data object information for library project by this way:
```
data "harbor_project" "main" {
    name    = "library" 
}

output "project_id" {
    value = data.harbor_project.main.id
}
```

but I got this error:
```
Error: strconv.ParseBool: parsing "": invalid syntax

  on template.tf line 49, in data "harbor_project" "main":
  49: data "harbor_project" "main" {
```

- version : 2.0.5

**Comment by sshah90** [comment]
@wrighbr facing same issue with project import statement, not sure if your PR covers that or not.

Command:
`terraform import -var-file ../xx/xxx/terraform.tfvars harbor_project.main[0] /projects/1`

Error:

```
2021/03/16 10:19:43 [ERROR] eval: *terraform.EvalRefresh, err: strconv.ParseBool: parsing "": invalid syntax
2021/03/16 10:19:43 [ERROR] eval: *terraform.EvalSequence, err: strconv.ParseBool: parsing "": invalid syntax
```

Version:
- bestseller/harbor v2.0.7
- Terraform 0.13.5

**Comment by wrighbr** [comment]
@sshah90 what does your terraform code look like for harbor_project.main[0]

**Comment by wrighbr** [comment]
@sshah90 if you have already created these resources in harbor manually and you are trying to import them into terraform I was able to do this with the latest provider and the below command.

terraform import 'harbor_project.main[1]' /projects/2

**Comment by sshah90** [comment]
@wrighbr Thanks for the input.

As Harbor is in the initial phase on our side, we just destroyed and recreate it.
