### ISSUE TITLE
Authentication is not working for harbor instance which is behind an OIDC provider

### ISSUE THREAD

**Issue by MrinalKantiGhosh** [BESTSELLER/terraform-provider-harbor#96]
Hello,
We have a Harbor instance running behind an OIDC provider/SSO. When I am trying to import or provision any object, I am constantly getting 401 UNAUTHORIZED even though username/password is correct.

Code

```
terraform {
  required_providers {
    harbor = {
      source = "BESTSELLER/harbor"
      version = "2.0.5"
    }
  }
}

provider "harbor" {
  url      = "URL"
  username = "USERNAME"
  password = "PASSWORD"
}

resource "harbor_project" "mbd-otr-de" {}
```

Output

```
Error: [ERROR] unexpected status code got: 401 expected: 200
 {"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorized"}]}
```

**Comment by wrighbr** [comment]
have you tired using the harbor admin password?

**Comment by MrinalKantiGhosh** [comment]
Yeah, still same result. We checked, and it was a problem from Harbor side with OIDC provider.

**Comment by esantoro** [comment]
hi @MrinalKantiGhosh I'm having a similar problem, except that we're using LDAP instead of OIDC.

How did you solve this issue ?

**Comment by MrinalKantiGhosh** [comment]
@esantoro we found out that harbor was not able to get auth_token from OIDC provider which results in 401. We had to upgrade harbor to 2.2
