### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by fl-max** [BESTSELLER/terraform-provider-harbor#98]
**Is your feature request related to a problem? Please describe.**
Hard to tell without going through commits as what has changed between releases

**Describe the solution you'd like**
A `CHANGELOG.md` managed that follows [KeepAChangeLog.com](https://keepachangelog.com/en/1.0.0/). Ideally this would be attached to each release's details.

**Describe alternatives you've considered**
Going through commits

**Additional context**
See most open source projects for examples.

**Comment by wrighbr** [comment]
@OrKarstoft can you look into this when you get a change
https://goreleaser.com/customization/release/#custom-release-notes

**Comment by wrighbr** [comment]
We have started using the build in change log from github to produce changes
